### ISSUE TITLE
Tracking Issue for Commands

### ISSUE THREAD

**Issue by patrickisgreene** [little-dude/xi-tui#70]
#69 is merged we have the ability to run commands from the TUI. So we'll need to start discussing what commands should be implemented, what a command sould look like anyway.

In #69 for Command structure i chose to have 2 forms of each command a 'long' and 'short' version, so for example to save the current buffer you could type 's' or 'save' and they are seen as the same command. But is this really the best way to go?

Here is a list of possible commands that xi-core already does for us(but we dont implement) and what i think there key bindings should be:
  - [x] quit ('q', 'quit')
  - [x] save ('s', 'save')
  - [ ] close ('c', 'close')
  - [x] backspace ('b', 'back')
  - [x] delete ('d', 'delete')
  - [x] open file ('o', 'open')
  - [x] next buffer ('bn', 'next-buffer')
  - [x] prev buffer ('bp', 'prev-buffer')
  - [ ] search ('?', 'search')
  - [ ] page down ('pd', 'page-down')
  - [ ] page up ('pu', 'page-up')
  - [ ] move left ('ml', 'move-left')
  - [ ] move right ('mr', 'move-right')
  - [ ] move up ('mu', 'move-up')
  - [ ] move down ('md', 'move-down')
  - [ ] left select ('sl', 'select-left')
  - [ ] right select ('sr', 'select-right')
  - [ ] up select ('su', 'select-up')
  - [ ] down select ('sd', 'select-down')
  - [ ] display themes? ('ts', 'themes')
  - [x] set theme ('t', 'theme')
